remove test git project

diff --git a/prepare b/prepare
--- a/prepare
+++ b/prepare
@@ -6,7 +6,7 @@
 rm -rf /tmp/latest-* stdout.txt stderr.txt players-api-*.jar
 
 #**************************************************************
-# Find the latest version of 'players-api-internal-test'
+# Find the latest version of 'players-api'
 #**************************************************************
 tempdir=$(mktemp -d -t latest-XXXXXXXXXX)
 result=$?
@@ -36,7 +36,7 @@ REPOSITORY_URL="https://server.rsmaxwell.co.uk/archiva/repository"
 REPOSITORYID="build"
 REPOSITORY="build"
 GROUPID="com.rsmaxwell.players"
-ARTIFACTID="players-api-internal-test"
+ARTIFACTID="players-api"
 PACKAGING="zip"
 
 URL=${REPOSITORY_URL}/${REPOSITORY}/
@@ -94,8 +94,8 @@ if [[ ! ${line} =~ ${regex} ]]; then
     exit 1
 fi
 
-players_api_internal_test_version="${BASH_REMATCH[1]}"
-echo "players_api_internal_test_version: ${players_api_internal_test_version}"
+players_api_version="${BASH_REMATCH[1]}"
+echo "players_api_version: ${players_api_version}"
 
 mvn --batch-mode dependency:resolve 1>stdout.txt 2>stderr.txt
 result=$?
@@ -129,43 +129,19 @@ fi
 #**************************************************************
 # Resolve 'players-api' and its testing addons
 #**************************************************************
-VERSION="${players_api_internal_test_version}"
+VERSION="${players_api_version}"
 PACKAGING="zip"
 
-filename=${HOME}/.m2/repository/${GROUPID//.//}/${ARTIFACTID}/${VERSION}/${ARTIFACTID}-${VERSION}.${PACKAGING}
-if [ ! -f ${filename} ]; then
-    echo "Error: $0[${LINENO}]"
-    echo "result: ${result}"
-    echo "file not found: ${filename}"
-    exit 1
-fi
 
-versionjson=$(java -cp ${filename} com.rsmaxwell.players_test.Version)
-result=$?
-if [ ! ${result} == 0 ]; then
-    echo "Error: $0[${LINENO}]"
-    echo "result: ${result}"
-    exit 1
-fi
-
-players_api_version=$(echo ${versionjson} | jq -r .players_api_version)
-result=$?
-if [ ! ${result} == 0 ]; then
-    echo "Error: $0[${LINENO}]"
-    echo "result: ${result}"
-    exit 1
-fi
 
 pathname="./version"
 cat >${pathname} <<EOT2
-export players_api_internal_test_version=${players_api_internal_test_version}
 export players_api_version=${players_api_version}
 EOT2
 
 #**************************************************************
 # Resolve the version of 'players-api' needed for testing
 #**************************************************************
-VERSION="${players_api_version}"
 
 mvn --batch-mode dependency:get \
         -Dartifact=${GROUPID}:${ARTIFACTID}:${VERSION}:${PACKAGING} \
@@ -181,6 +157,14 @@ if [ ! ${result} == 0 ]; then
     echo "----[ stderr ]--------------------------"
     cat stderr.txt
     echo "----------------------------------------"
+    exit 1
+fi
+
+filename=${HOME}/.m2/repository/${GROUPID//.//}/${ARTIFACTID}/${VERSION}/${ARTIFACTID}-${VERSION}.${PACKAGING}
+if [ ! -f ${filename} ]; then
+    echo "Error: $0[${LINENO}]"
+    echo "result: ${result}"
+    echo "file not found: ${filename}"
     exit 1
 fi
 
@@ -200,6 +184,14 @@ if [ ! ${result} == 0 ]; then
     echo "----[ stderr ]--------------------------"
     cat stderr.txt
     echo "----------------------------------------"
+    exit 1
+fi
+
+filename_test=${HOME}/.m2/repository/${GROUPID//.//}/${ARTIFACTID}/${VERSION}/${ARTIFACTID}-${VERSION}-${CLASSIFIER}.${PACKAGING}
+if [ ! -f ${filename} ]; then
+    echo "Error: $0[${LINENO}]"
+    echo "result: ${result}"
+    echo "file not found: ${filename}"
     exit 1
 fi
 
